pipeline {
    agent any
    
    stages {
        stage('terraform infa create') {
            steps {
                sh """
                cd solution
                terraform init
                terraform destroy --auto-approve"""
            }
        }
       
    }
}
